### ISSUE TITLE
Sink.StopOnDisconnect is blocked forever in TopologyBuilder.AddSelectUnionStmt

### ISSUE THREAD

**Issue by nobu-k** [sensorbee/sensorbee#101]
I encountered an issue in `bql.TopologyBuilder.AddSelectUnionStmt`:

1. Connect Sink to (i.e. SELECTing from) a Source that generates tuples very quickly
2. The pipe between the Source and the Sink becomes full
3. Call `StopOnDisconnect` of `Sink` but it's blocked until the `Sink` actually start consuming tuples
4. Because a chan is not returned from `bql.TopologyBuilder.AddSelectUnionStmt`, nobody can consume a tuple from the pipe and the method is blocked forever

**Comment by disktnk** [comment]
thanks for analysis!
