### ISSUE TITLE
Converting string "false" to bool value

### ISSUE THREAD

**Issue by rimms** [sensorbee/sensorbee#134]
In BQL, string "false" is converted to bool `true` like JavaScript.
* https://godoc.org/gopkg.in/sensorbee/sensorbee.v0/data#ToBool

I think this specification is not user-friendly when using BQL.

My idea is the following:

``ToBool(value String)`` returns `false` if value is empty or "false".

How about this idea?

**Comment by nobu-k** [comment]
https://github.com/sensorbee/sensorbee/issues/84

Yes, we actually think so, too. In that case, however, I'm still not sure whether a non-empty string should be converted to true or false. We should probably follow common semantics that major databases support.

**Comment by rimms** [comment]
Thanks.

duplicate of #84. I close this.
