### ISSUE TITLE
bql box test sometimes fail

### ISSUE THREAD

**Issue by disktnk** [sensorbee/sensorbee#50]
"bql_box_test.go" https://github.com/sensorbee/sensorbee/blob/595bc3ef0de033e784cd0231bc307aa4e83c8850/bql/bql_box_test.go has time/sampling dependency tests and sometimes fails by processing speed.

**require to fix**

1. "Given a BQL statement with an EVERY 1 MILLISECONDS clause" L273
 * sometimes all 2 tuples not emit within 1ms, and the sink writes tuple more than 2 (fail at L294)

2. "Given a BQL statement with an EVERY 1 MILLISECONDS and LIMIT clause" L301
 * sometimes all 2 tuple not emit within 1ms, and the sink doesn't write the last emitted tuple("int"=4) (fail at L323)

3. "Given a BQL statement with a SAMPLE clause" L328
 * In the box, emitting only 10 tuple is rarely but sometimes a tuple not emitted between L345 and L346, so at L346 assert can not pass.
 * `si.Wait(10)` (L345) must be fixed because the box emit only less than 10 tuples (but rarely), L369 is same.

**pending**

* "Given a BQL statement with an EVERY 10 MILLISECONDS clause" L245,
 * should also fix because of using `time.Sleep` but this test rarely fails, so not included in this issue.

**Comment by disktnk** [comment]
**fixing plan** (just a proposal)

1. => change "dummy" source to "ticked_dummy" which generates tuples in intervals. "source" generates tuples with in 1[ms] intervals and "box" emits tuples with `[EVERY 1.5 MS]`, then the test can check the difference between 2 tuples which written to "sink"; the difference should be about 1.5[ms]. It is difficult to set tolerance and I think this change is overdone in bql_box_test.

2. => change "dummy" source to "ticked_dummy" (same as 1.) and "source" generates tuples in 1[ms] intervals. "box" is set as emitting with `[LIMIT n]` and the test confirm that  "sink" should receive "n" tuples.

3. => Add status in "duplicate" UDSF and `Wait` method which can wait until ​*n*​ tuples have been emitted. The test checks received tuple count after the UDSF is done streaming all tuples.

**Comment by nobu-k** [comment]
EVERY and SAMPLE are still unofficial features and they'll likely be get removed or their specification may be changed a lot. So, let's just remove those tests by `SkipConvey` for now.

**Comment by disktnk** [comment]
> they'll likely be get removed or their specification may be changed a lot

OK, I see.
