### ISSUE TITLE
Remove default sensorbee command

### ISSUE THREAD

**Issue by nobu-k** [sensorbee/sensorbee#55]
The default `sensorbee` command in the repository is kind of useless because it doesn't have any plugin. It only increases the number of sensorbee commands in users' environment. So, I think it should not be be installed at the moment.

**Comment by tgpfeiffer** [comment]
I wonder if it would be nice to have an minimal executable that can be used (only) as a shell/client (like the current `sensorbee` file), maybe with a different executable name, like `sbclient` or so?

**Comment by nobu-k** [comment]
That sounds nice! What's a good name for it? `sbclient` or `sbshell`?

**Comment by tgpfeiffer** [comment]
`bql`? Or `bqlient` :-)

**Comment by disktnk** [comment]
`sbclient` (or `bql` , `bqlent` ...) wlll be an alias of `sensorbee shell` ? or use as `sbclient shell` ?

**Comment by nobu-k** [comment]
`bql` sounds good to me.

I think the client command shouldn't be a alias or symlink of a `sensorbee` command. This issue is about removing the default `sensorbee` command because it's confusing for users to have it installed to somewhere accessible in PATH. So, the new client command should not depend on a `sensorbee` command.

**Comment by disktnk** [comment]
sorry, "alias" is caused misunderstanding, my question is the usage of the minimal sensorbee command.

```
bql
> use hoge
hoge>
```

or

```
bql shell
> use hoge
hoge>
```

**Comment by nobu-k** [comment]
I see. I think the client command shouldn't have subcommands. In your example, the former is better. What do you guys think?

**Comment by tgpfeiffer** [comment]
I think `bql` should be a program with the same function as `sensorbee shell`.
