### ISSUE TITLE
"2.5"::int fails

### ISSUE THREAD

**Issue by tgpfeiffer** [sensorbee/sensorbee#57]
The documentation states

> When converting a string value into an int value, CAST operator first tries to parse it as an integer to guarantee better precision. If the parsing fails, it tries to parse the string value as a float value and then converts the result to an int value.
>
>     "1"::int   -- => 1
>     "2.5"::int -- => 2

But actually, `EVAL "2.5"::int;` results in an error: "strconv.ParseInt: parsing \"2.5\": invalid syntax".

I am not sure if this is a bug in the documentation or the code.

**Comment by nobu-k** [comment]
I think we had a discussion like:

* BQL should be as type-safe as possible and "2.5" should not be parsed as int.
* Meanwhile, JSON doesn't distinguish int and float, and some JSON libraries could encode 1 into 1.0. This type safe specification might be inconvenient for such cases.
* However, there's a workaround like `(str::float)::int`, so we should adopt the type-safe way for now.

**Comment by nobu-k** [comment]
So, this is a bug of the documentation.

**Comment by tgpfeiffer** [comment]
I fixed this bug in the documentation (https://github.com/sensorbee/docs/commit/40c542e2c9d217b20ef0f79f167c1975655dab0b#diff-8650db26e8fb91d1daaae8dd43817a9eR332) and merged it.
