### ISSUE TITLE
Implement array_length function

### ISSUE THREAD

**Issue by tgpfeiffer** [sensorbee/sensorbee#59]
``array_length`` is a frequently requested function. Basically ``count()`` can be used as a backend implementation, but without the requirement for aggregation.

**Comment by nobu-k** [comment]
How about this:

1. Provide `array_length` first
2. Provide `length` or `size` next (or when it's requested)
3. Provide generic `length` that works for both an array and a map when it's requested

Providing `array_length` doesn't conflict with 3 and is requested at the moment. So, I'll implement it.

**Comment by tgpfeiffer** [comment]
I think the order is good. We could have `array_length` as suggested and also `map_length` and later on add a function `length` that dispatches to `array_length`, `map_length` or `char_length`.

NB. In the documentation, I think we should add a comment about whether NULLs in the array are counted or not.

**Comment by nobu-k** [comment]
Good point.

Sorry, I didn't have time today and won't this week. Could you think of the spec and implement it?
