### ISSUE TITLE
Asymmetric bool conversion

### ISSUE THREAD

**Issue by disktnk** [sensorbee/sensorbee#84]
`(false::string)::bool` is true now.

PostgreSQL supports some string values for bool like 't', 'f', 'yes', 'no', and so on. BQL should perhaps support them, too.

**Comment by nobu-k** [comment]
I think supporting the same semantics as PostgreSQL's is fine: https://www.postgresql.org/docs/current/static/datatype-boolean.html .

Performing the type cast with invalid values fails:

```
# SELECT '2'::boolean;
ERROR:  invalid input syntax for type boolean: "2"
LINE 1: SELECT '2'::boolean;
               ^
```

```
# SELECT * FROM str;
 c
---
 t
 f
 0
 1
(4 rows)

# SELECT c::boolean FROM str;
 c
---
 t
 f
 f
 t
(4 rows)

# INSERT INTO str VALUES ('2');
INSERT 0 1
# SELECT * FROM str;
 c
---
 t
 f
 0
 1
 2
(5 rows)
# SELECT c::boolean FROM str;
ERROR:  invalid input syntax for type boolean: "2"
```

This will be a breaking change, so I'll apologize for the inconvenience in advance orz

**Comment by tgpfeiffer** [comment]
In this case I think we borrowed the semantics from Python, where any string except `""` converts to `True`.

**Comment by nobu-k** [comment]
Yes, we did, but it wasn't practical in BQL.
