### ISSUE TITLE
BQL parser leaks a goroutine.

### ISSUE THREAD

**Issue by nobu-k** [sensorbee/sensorbee#96]
gw:

When parsing large integer (>= 2^63), the parser leaks a goroutine due to peg. The leaked goroutine is https://github.com/sensorbee/sensorbee/blob/bffc8059fd9e4dbf156543c8c369ce7277da6a25/bql/parser/bql.peg.go#L936. The parser stops to read the channel s after attempting to parse large integer, so the goroutine may block forever. Both of the sender and the receiver are generated by peg.

**Comment by disktnk** [comment]
The generated code (linked in the above comment ) is improved on new PEG library and the new generated code is merged with #132 , so close this issue. When a similar problem is occurred, please create a new issue.
